### ISSUE TITLE
FIX: about 4% of flips are happening late

### ISSUE THREAD

**Issue by rkmaddox** [LABSN/expyfun#251]
@lkishline and I are getting an AV experiment set up, which involves some carefully timed flashes. We are timing these flips such that there is a first flip when `start_stimulus` is called and all other flips use the `when` argument relative to that one. We have set it up such that the time we pass for `when` is equal to the initial flip time + a time corresponding to a whole number of frames - `0.9 / frame_rate`. This should very reliably put the flips where we want them.

Instead, we are losing about 10% of trials because some trials have late flips, sometimes by even more than one frame. @Eric89GXL @drammock, do you guys have any idea how the flip timing could be made more reliable?

**Comment by rkmaddox** [comment]
I should add that all that's happening between flips is `draw()` commands.

**Comment by Eric89GXL** [comment]
We should figure out where the problem is. I suspect the `draw` calls are taking too much time.

How many `draw` commands are you emitting between flips? Try commenting all of them out -- does it fix the timing? Comment out half, is it still reliably good? If so, then it means the drawing needs to be more efficient. There are some ways we can do that by being smarter about OpenGL. If that doesn't fix the problem, then I'll have to think harder about what the problem may be. Perhaps the OS is doing something stupid.

**Comment by rkmaddox** [comment]
Either one or two draws, never more (i guess three, since the fixation dot draw is actually two draws). @lkishline, tomorrow let's try commenting out everything but the flips and see if the timing improves.

**Comment by lkishline** [comment]
Okay sounds good, I'll try it in the morning.

**Comment by lkishline** [comment]
Alright - on the block I ran with all the draw calls commented out I still got 8 trials I would of had to toss (8 late flips, two were in the same trials). On the block I ran with half the draw calls commented out I got 9 trials that had late flips - two of them had a couple late frames. 
A side note about the one that I commented out half of them on - @rkmaddox I got a wider range of time stamps. For example instead of 16's or 33's I would get more 15's, 17's, and 32's. Not sure what that means or if it is down to chance for that. I kept the output in two different interpreters downstairs.

**Comment by lkishline** [comment]
Forgot to say I have 108 trials/block.

**Comment by rkmaddox** [comment]
I don't think we need to worry about 15s and 32s, that still isn't a missed frame. Can you check to see that none of the frames came _early_?

**Comment by lkishline** [comment]
None of them came early. All the ones I mentioned about came one or two frames late.

**Comment by Eric89GXL** [comment]
Hmm. I wonder if there is some process on the computer that is interrupting things. 

Another possibility is that the `wait_secs` [function] (https://github.com/LABSN/expyfun/blob/master/expyfun/_utils.py#L671) that is [called here] (https://github.com/LABSN/expyfun/blob/master/expyfun/_experiment_controller.py#L1590) could be factored out. We could try to make the `wait_until` function be more precise in how it waits, since it's the one doing the heavy lifting for `flip(when)`. For example, instead of taking a difference and using that in `wait_secs()`, the method `wait_until` itself could have a loop itself taking differences at the start of each iteration, and could only dispatch window events if the amount of time to wait is longer than some small amount (we could try 5, 10, or 50 ms).

**Comment by rkmaddox** [comment]
In `timeit.py` I find this code:

```python
if sys.platform == "win32":
    # On Windows, the best timer is time.clock()
    default_timer = time.clock
else:
    # On most other platforms the best timer is time.time()
    default_timer = time.time
```

How bad is `time.time` on windows, and could it be that's what it's using, since it is likely not `win32` for 64-bit Windows 7?

Either way, I am writing up a test script for `wait_until` and `wait_secs` to see how accurate they are on the various systems.

**Comment by rkmaddox** [comment]
Ah, never mind. I just realized that `timeit.py` is a python built-in, not one of ours.

**Comment by rkmaddox** [comment]
This gives pretty accurate timing on my linux machine: https://gist.github.com/rkmaddox/88e692527926325719a3.

Only about 1 in 1000 wait times is late by over a ms, and it is never later than 2 ms. I'll go run it on the behavioral rig before replacing its fan.

**Comment by rkmaddox** [comment]
Timing on the windows computer was even better. NO delays longer than 1 ms. All but 4 of the 4000 tests happened within 0.2 ms of the target time. I'm actually a little suprised that both computers weren't more accurate, but the problem certainly doesn't seem to be with `wait_secs` nor by extension `wait_until`.

**Comment by drammock** [comment]
@rkmaddox's gist gives me similar results on my machine (biggest delay around 1.3 ms, only about half a dozen points appreciably off the x axis). In contrast, my tests with `flip()` this morning (including `ec.estimate_screen_fs`) are showing frame rates of around 30 Hz, even though `xrandr` and `glxgears` are both showing 60 Hz.  Probably unrelated?

**Comment by rkmaddox** [comment]
Unrelated. That's a weird thing with most linux desktop managers and `expyfun` not playing nice.

I just tried setting the process to high priority instead of normal and running Lindsey's code again. Still 7 missed frames, which is within the noise (no improvement).

**Comment by rkmaddox** [comment]
Running it at high priority with all the `draw()` commands commented out yielded no missed frames. Not sure if high priority was what did it, but it appears that the problem is in the drawing methods, and these can sometimes take too long, sometimes by even more than a frame.

**Comment by rkmaddox** [comment]
Just ran on normal priority, all `draw`s removed. No missed frames. So problem is definitely with `draw` method.

**Comment by drammock** [comment]
sigh...  pyglet strikes again.

**Comment by lkishline** [comment]
Sorry guys, I guess I did not actually comment out all the draw commands this morning.

**Comment by rkmaddox** [comment]
Oooooooookkkkkkkkkk something odd is happening.

Ran this [gist](https://gist.github.com/rkmaddox/2453d1a38bb246d10ea9) on my linux computer, testing the draw time for 1000 iterations. Almost all of them were 0.8 ms, but a special few were much longer, in the 4 to 10 ms range. What is so odd, is that it is deterministic which ones take too long...

For example, draw number 653 always takes around 10 ms, even though the ones nearby are normally timed. I ran the thing several times and this was always the case. This was true, _even when I inserted a random pause between 0 and 1 ms after every draw_. This means that the draw delay is a function of the number of draws that have come before it. It also holds whether you `flip` between draws or not.

**Comment by rkmaddox** [comment]
The `draw` command imports `pyglet`. Is it possible this every now and then takes a long time to do?

**Comment by rkmaddox** [comment]
Moving the `pyglet` import to the top of the `visual` module instead of being imported in the `draw` command does not change anything.

**Comment by rkmaddox** [comment]
Running the test with `Rectangle` and `Triangle` gives the same results (as each other, not as with `circle`). This suggests that it is not the number of GL points / faces drawn that causes the problem.

**Comment by lkishline** [comment]
When I run it on my Linux I don't see any pattern to the draw's that take longer than 5ms, other than most commonly it is the first one that is over 10ms (but not consistently).

That is probably not helpful.

**Comment by drammock** [comment]
@rkmaddox and I have tried several different numbers of vertices by
manipulating `n_edges` in the call to `Circle` and are seeing many delays
>2ms and some as high as 24.  Seems to be deterministic for any chosen
number of vertices, and in many cases it's the same iterations that are
problematic whether `n_edges` is 5 or 6, for example.

**Comment by rkmaddox** [comment]
@lkishline it's not unhelpful. Means that we really should check it out on the experimental computer specifically, since that is the platform on which we really need the timing to be perfect. It's especially odd, since my and Dan's computers behave very similarly.

**Comment by lkishline** [comment]
Ran on experimental computer several times with 'n_edges' as 5 or 6 and flip() on, other than the first draw being really high (around 20ms) there isn't much to report. On one of the runs draw 89 was high but haven't seen anything since. 

Of course with my track record today...maybe someone should verify...
I kept all the interpreters up this time so we can go back and check.

**Comment by drammock** [comment]
[Another gist](https://gist.github.com/drammock/cafd0d9de9b129c49659) showing the effect of number of edges on the circle.

**Comment by rkmaddox** [comment]
Whaaaaaaat. So a temporary fix might be upping the edges to 500? Weird.

**Comment by drammock** [comment]
note the baseline shift though...  *every* draw takes ~2ms

**Comment by rkmaddox** [comment]
Yeah, noted, but if it's reliable we can account for it. For this experiment we always have at least 16 ms to work with.

**Comment by Eric89GXL** [comment]
Both booth computers should have 144 Hz monitors, so you'd have 7 ms between flips or 14 between two flips. Are you running the experiment on a laptop or something?

Adding more edges fixing the problem is bizarre, but if it works +1 for using it for this experiment. Let's keep this issue open, though, because I suspect there are ways we can make the drawing more efficient and thus speed it up. Drawing with `vispy` is an option, but I think I can change the drawing code to be faster in some ways already. I'll try to find time next week or the week after to do it.
